name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2toolchain:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk add build-base git bash

      - name: Compile Supertux
        run: |
          make .cpp.o
          make all

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ps2sdk-supertux
          path: supertux.elf

      - name: Debug Artifact
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failure
          path: ./
